Fix compile error on unsigned 64-bit enum int constants
Related to https://github.com/kaitai-io/kaitai_struct/issues/1288
(I consider the change in this commit to be a prerequisite for its full
implementation; without it, enum support would be unnecessarily limited
to *signed* 64-bit integers.)

Fixes the compile error of the EnumLongRangeU test format after
https://github.com/kaitai-io/kaitai_struct_tests/commit/b88e1f53d0b8a785abae3604303f6c11d44ee6e4

This commit ensures that the compiler accepts integer constants between
`2**63` (`0x8000_0000_0000_0000` or 9223372036854775808) and `2**64 - 1`
(`0xffff_ffff_ffff_ffff` or 18446744073709551615) in enum definitions.
This allows defining enums with integer values from the entire range of
the unsigned 64-bit integer type in some target languages (where it is
not broken for another reason).

Previously, attempting to use an integer constant outside the range of
the signed 64-bit integer type (i.e. over `2**63 - 1`) in the enum
definition resulted in the following compile error:

```
formats/enum_long_range_u.ksy: /enums/constants:
        error: expected int, got 18446744073709551615 (class java.math.BigInteger)
```