KSError: added ConversionError and relevant mappings to exceptions in languages where this will be supported (part of effort requires for https://github.com/kaitai-io/kaitai_struct/issues/1023)